import type { Badge, GamificationConfig, Reward } from '../types/gamification';

export const GAMIFICATION_CONFIG: GamificationConfig = {
    xpPerLevel: 1000,
    streakBonus: 50,
    dailyLoginXp: 100,
    courseCompletionXp: 500,
    investmentXp: 200,
    communityXp: 50,
    badgeRarities: {
        common: 100,
        uncommon: 250,
        rare: 500,
        epic: 1000,
        legendary: 2500,
    },
};

export const BADGES: Badge[] = [
    // Learning Badges
    {
        id: 'badge_001',
        name: 'First Steps',
        description: 'Complete your first course module',
        icon: 'book-open',
        rarity: 'common',
        xpReward: 100,
        category: 'learning',
        unlocked: false,
    },
    {
        id: 'badge_002',
        name: 'Course Master',
        description: 'Complete 5 courses',
        icon: 'graduation-cap',
        rarity: 'uncommon',
        xpReward: 500,
        category: 'learning',
        unlocked: false,
    },
    {
        id: 'badge_003',
        name: 'Knowledge Seeker',
        description: 'Complete all beginner courses',
        icon: 'lightbulb',
        rarity: 'rare',
        xpReward: 1000,
        category: 'learning',
        unlocked: false,
    },
    {
        id: 'badge_004',
        name: 'E-commerce Scholar',
        description: 'Complete all courses in the platform',
        icon: 'mortar-board',
        rarity: 'epic',
        xpReward: 2500,
        category: 'learning',
        unlocked: false,
    },

    // Investment Badges
    {
        id: 'badge_005',
        name: 'First Investment',
        description: 'Make your first investment',
        icon: 'coins',
        rarity: 'common',
        xpReward: 200,
        category: 'investment',
        unlocked: false,
    },
    {
        id: 'badge_006',
        name: 'Portfolio Builder',
        description: 'Invest in 3 different pools',
        icon: 'chart-line',
        rarity: 'uncommon',
        xpReward: 500,
        category: 'investment',
        unlocked: false,
    },
    {
        id: 'badge_007',
        name: 'Wealth Creator',
        description: 'Earn $1000 in investment returns',
        icon: 'money-bill-wave',
        rarity: 'rare',
        xpReward: 1000,
        category: 'investment',
        unlocked: false,
    },

    // Community Badges
    {
        id: 'badge_008',
        name: 'Community Member',
        description: 'Join your first community group',
        icon: 'users',
        rarity: 'common',
        xpReward: 100,
        category: 'community',
        unlocked: false,
    },
    {
        id: 'badge_009',
        name: 'Helping Hand',
        description: 'Answer 10 community questions',
        icon: 'hand-holding-heart',
        rarity: 'uncommon',
        xpReward: 300,
        category: 'community',
        unlocked: false,
    },

    // Milestone Badges
    {
        id: 'badge_010',
        name: 'Week Warrior',
        description: 'Maintain a 7-day login streak',
        icon: 'trophy',
        rarity: 'common',
        xpReward: 200,
        category: 'milestone',
        unlocked: false,
    },
    {
        id: 'badge_011',
        name: 'Month Master',
        description: 'Maintain a 30-day login streak',
        icon: 'medal',
        rarity: 'rare',
        xpReward: 1000,
        category: 'milestone',
        unlocked: false,
    },
    {
        id: 'badge_012',
        name: 'EcommXpert Legend',
        description: 'Achieve level 50 and complete all badges',
        icon: 'crown',
        rarity: 'legendary',
        xpReward: 5000,
        category: 'milestone',
        unlocked: false,
    },
];

export const REWARDS: Reward[] = [
    {
        id: 'reward_001',
        name: 'Premium Course Access',
        description: 'Unlock one premium course of your choice',
        cost: 1000,
        type: 'premium_content',
        available: true,
    },
    {
        id: 'reward_002',
        name: 'Investment Fee Waiver',
        description: 'Waive fees on your next investment',
        cost: 2500,
        type: 'discount',
        available: true,
    },
    {
        id: 'reward_003',
        name: 'Early Access Features',
        description: 'Get early access to new platform features',
        cost: 5000,
        type: 'feature_unlock',
        available: true,
    },
    {
        id: 'reward_004',
        name: 'EcommXpert Merchandise',
        description: 'Receive official EcommXpert merchandise',
        cost: 10000,
        type: 'physical',
        available: true,
    },
];